name: 'Properties IO'
description: 'read from, and write to **.properties file'
inputs:
  file:
    description: 'the .properties file to work with'
    required: true
    default: './app.properties'
  read-from:
    description: 'the field to read from'
  write-to:
    description: 'a space separated list of field=value pairs to write to'

outputs:
  value: 
    description: 'the value read from the field specified with read-from'
runs:
  using: 'node12'
  main: 'dist/index.js'
